name: Testing
on:
  push:
    branches:
      - '*'
jobs:
  run-wacat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone the wacat repository
        run: git clone https://github.com/mikesmallhelp/wacat.git
      - name: Navigate to the wacat directory
        run: cd wacat
      - name: Install Playwright
        run: npm install && npx playwright install --with-deps
      - name: Build and install wacat command
        run: npm run build && npm install -g
      - name: Run the test command
        run: wacat test https://mikesmallhelp-test-application.vercel.app/


